name: Scrape latest debe data

on:
  schedule:
    - cron:  '30 5 * * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    
    - name: Fetch debe data with node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm start
    
    - name: Commit and push if it changed
      run: |-
        git config --local user.name "Automated"
        git config --local user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push origin main
