name: Scrape latest debe data

on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    
    - name: Fetch debe data with node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm start
    
    - name: Commit and push if it changed
      run: |-
        git --local config user.name "Automated"
        git --local config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push origin main